spring.application.name=gpaiements
spring.datasource.url=jdbc:postgresql://postgresql-gestion-chambres-salles.alwaysdata.net:5432/gestion-chambres-salles_bdd
spring.datasource.username=gestion-chambres-salles_clement
spring.datasource.password=@R7LMPV@s4x8SZB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=LaCleDuProjetSecrete13131311313131
app.jwt.expiration=3600000

app.auth.admin-user=admin
app.auth.admin-mdp=motdepasse131

logging.level.org.springframework.security=DEBUG